name: your_voice_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.5
  speech_to_text: ^7.3.0
  shared_preferences: ^2.5.3
  file_picker: ^10.3.8
  uuid: ^4.5.2
  google_sign_in: ^7.2.0
  http: ^1.6.0
  kakao_flutter_sdk_user: ^2.0.0+1
  flutter_secure_storage: ^10.0.0
  audioplayers: ^6.6.0
  record: ^6.2.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/login_hero.png
    - assets/images/voice_thumb_upload.png
    - assets/images/voice_thumb_room.png
    - assets/images/voice_thumb_market.png
